# SonarQube project configuration — product-service
# Self-hosted SonarQube (no sonar.organization needed)
sonar.projectKey=shopnova-product-service
sonar.projectName=ShopNova Product Service
sonar.projectVersion=1.0

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.test.js,**/*.spec.js

sonar.javascript.lcov.reportPaths=coverage/lcov.info
